### PR TITLE
Added openid auth example

### PR DESCRIPTION
**Pull request by sker65**
Added an example of authentication using an openid access token. Token gets validated and grant is provided as "server data" as a basis for permissions in a permission plugin.

Uses the keycloak-connect client library but should work with every compliant openid server, not just keycloak

### CODE REVIEW

**Review by yasserf — COMMENTED** [review]
This is awesome! Wouldn’t you want to publish it as a package though so people can just use it directly?

**Comment by sker65** [comment]
you mean publish it on npm.js? Okay I could do that as well, I was hesitating 'cause I didn't find any example on npm where plugins as packages are published.
You could still add to your repo as example if you like.
I also have a permission plugin that controls subscription to events based on roles in access tokens, which is more or less very straight forward, if you have the first step.

**Comment by yasserf** [comment]
Generally all you need to publish your own plugin is the following:

1) Make sure in package.json you main is pointing to the plugin entry point: `"main": "dist/src/provider.js",`

2) The plugin needs to be exported as default (very important)

3) npm publish

4) To install, simply:

```
auth:
  - path: npm-module-name
```

Note: this only works with by running deepstream via npm, if you want to use it via docker you simply need to have a custom docker file like:

```
FROM deepstreamio/deepstream.io:latest
RUN npm install your-package-name
```

**Comment by yasserf** [comment]
You can also raise a PR adding documentation here:

```
https://github.com/deepstreamIO/deepstream.io-website/tree/master/content/tutorials/65-community-plugins
```

Which should mirror the same structure for:

```
https://github.com/deepstreamIO/deepstream.io-website/tree/master/content/tutorials/60-plugins
```

Once that's in I can very easily add it to the tutorial page

**Comment by yasserf** [comment]
Thanks again!

**Pull request merged**
